---
### base tasks

- name: packages
  import_tasks: packages.yml

- name: firewall setup
  import_tasks: firewall.yml

- name: NTP server setup
  import_tasks: ntp.yml

- name: environment setup
  import_tasks: envsetup.yml

- name: SSH setup
  import_tasks: ssh.yml

- name: directories privileges
  file:
    path: "{{ item }}"
    state: directory
    mode: '0751'
  loop:
    - /
    - /etc
    - /home
    - /var
    - /var/log
    - /srv/www

# vi: set expandtab:
